spring.application.name=garage23

# Conexión a la base de datos (Puerto 3306 y creará la BD garage23 si no existe)
spring.datasource.url=jdbc:mariadb://localhost:3306/garage23?createDatabaseIfNotExist=true
spring.datasource.username=root
# Déjalo vacío si no le pusiste contraseña en tu ordenador. Si le pusiste "secreta", escríbela después del =
spring.datasource.password=secreta

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true

# JWT y Seguridad
jwt.secret=clave_super_secreta_para_el_taller_2026
jwt.access.expires=3600000
jwt.refresh.expires=604800000
jwt.issuer=garage23
frontend.url=http://localhost:4200